TypeError: move_activity() got multiple values for argument 'default' (#111)
* TypeError: move_activity() got multiple values for argument 'default'

* Implemented requested changes

* renamed tests

* positional arguments replaced by keyword arguments

* fixed apply_to method in modifiers.py

Co-authored-by: Jose De la Paz Noguera <Jose.DelaPazNoguera@arup.com>